{% set name = "panda-client" %}
{% set version = "1.5.83" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PanDAWMS/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b0890a9774e4644ec1b026c143dfdc83a459c84226f2a54128a74a4c436dc6d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pandatools

about:
  home: https://panda-wms.readthedocs.io/en/latest/
  summary: PanDA Client Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tmaeno
    - wguanicedew
    - yesw2000
