{% set name = "panda-client" %}
{% set version = "1.5.43" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PanDAWMS/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8403ec1a96b65fe76aa75022520764d331e708b2740b05c40a460ffe43d9cd1f 

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pandatools

about:
  home: https://panda-wms.readthedocs.io/en/latest/
  summary: PanDA Client Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tmaeno
    - wguanicedew
    - yesw2000
