{% set name = "panda-client" %}
{% set version = "1.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PanDAWMS/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 125766affa77dac1d63877e68f20e3024b8685d60dbb305b1f0f455255f8f34f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pandatools

about:
  home: https://panda-wms.readthedocs.io/en/latest/
  summary: PanDA Client Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tmaeno
    - wguanicedew
    - yesw2000
