{% set name = "panda-client" %}
{% set version = "1.4.83" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/panda-client-{{ version }}.tar.gz
  sha256: 05b820de636df799e6cf30d79989abdff5e32933f159ccee8b4e586f69df47ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pandatools

about:
  home: https://panda-wms.readthedocs.io/en/latest/
  summary: PanDA Client Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yesw2000
