{% set name = "panda-client" %}
{% set version = "1.5.79" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PanDAWMS/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 339472e80fd243afa1bc673f20b1819df6f8e8f83acbdf7d286a0bbe719bbe1b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pandatools

about:
  home: https://panda-wms.readthedocs.io/en/latest/
  summary: PanDA Client Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tmaeno
    - wguanicedew
    - yesw2000
