{% set name = "panda-client" %}
{% set version = "1.4.99" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PanDAWMS/{{ name }}/archive/refs/tags/1.4.99.tar.gz
  sha256: 5c1eb06997f961a2ce062bae9bc3649f4087c0e29ee2f54e842be75cf050176d 

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pandatools

about:
  home: https://panda-wms.readthedocs.io/en/latest/
  summary: PanDA Client Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
