{% set name = "panda-client" %}
{% set version = "1.4.82" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/panda-client-{{ version }}.tar.gz
  sha256: 3eb6187a2c2280b6fc2751eb666ac0df61092d77d211753f0cba527b5a555d07

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pandatools

about:
  home: https://panda-wms.readthedocs.io/en/latest/
  summary: PanDA Client Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yesw2000
