{% set name = "panda-client" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PanDAWMS/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: bf6b07e7242ddb1d96dd9f7c1ecbd329d0624dcd399e45a47f5f730b0b42a8ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pandatools

about:
  home: https://panda-wms.readthedocs.io/en/latest/
  summary: PanDA Client Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tmaeno
    - wguanicedew
    - yesw2000
